### PR TITLE
Sc 7536 fix test new chief

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Review by lucas-manuel — COMMENTED** [review]
Should we do a testFail for a same-block lock and free or is that redundant?

**Comment by gbalabasquer** [comment]
I think that is enough tested in the chief but not opposed if we want to add it.

**Review by lucas-manuel — APPROVED** [review]
I agree its tested enough in the chief

**Review by kmbarry1 — APPROVED** [review]
LGTM

**Pull request merged**
